WIP Onion path modal dialog and modal dialog refactor.
oxen-io/session-desktop pull request #1665
Opened 2021-05-26 00:07 UTC by warrickct

### First time contributor checklist:

* [ ] I have read the [README](https://github.com/loki-project/loki-messenger/blob/master/README.md) and [Contributor Guidelines](https://github.com/loki-project/loki-messenger/blob/master/CONTRIBUTING.md)

### Contributor checklist:

* [ ] My commits are in nice logical chunks with [good commit messages](http://chris.beams.io/posts/git-commit/)
* [ ] My changes are [rebased](https://blog.axosoft.com/golden-rule-of-rebasing-in-git/) on the latest [`clearnet`](https://github.com/loki-project/loki-messenger/tree/clearnet) branch
* [ ] A `yarn ready` run passes successfully ([more about tests here](https://github.com/loki-project/loki-messenger/blob/master/CONTRIBUTING.md#tests))
* [ ] My changes are ready to be shipped to users

### Description

2021-05-26 00:18 UTC, majestrate commented
this pulls in a package that does http requests to some remote server to fetch data, suggest using a local geoip database instead.

2021-05-26 01:18 UTC, Bilb commented on stylesheets/_modal.scss
> +          background-color: $color-loki-green;
you have to use themify to handle the theme switch:
```
  @include themify($themes) {
    background: themed('accent');
  }
```

2021-05-26 01:18 UTC, Bilb commented on stylesheets/_modal.scss
> +          background-color: #ff453a;
```
  @include themify($themes) {
    background: themed('danger');
  }
```

2021-05-26 01:18 UTC, Bilb commented on ts/session/onions/index.ts
> +    window.inboxStore?.dispatch(updateOnionPaths(goodPaths[0]));
probably a good idea to check for the length of goodpath and dispatch [] or undefined if length is not > 0

2021-05-26 01:18 UTC, Bilb commented on ts/state/ducks/onion.tsx
> +export const defaultOnionReducer = reducer;
can you make defaultOnionReducer to defaultOnionPathReducer and the filename be onionPath.tsx

2021-05-26 01:18 UTC, Bilb commented on ts/components/session/ActionsPanel.tsx
> +    iconColor = hasOnionPath ? Constants.UI.COLORS.GREEN : Constants.UI.COLORS.DANGER;
rather use the theme here.
just like we have themify for css, in those components you can use

useTheme to get the current theme (and refresh on theme switch) and get the color to use with theme.colors.xxx

2021-05-26 01:18 UTC, Bilb commented on ts/components/session/ActionsPanel.tsx
you can keep this like that, but can you put it in another component in ActionPanel.tsx so we keep this part cleaner

2021-05-26 01:18 UTC, Bilb commented on ts/components/session/ActionsPanel.tsx
> +  }, 1000);
you should be able to get rid of that once you have the dispatch where it is needed

2021-05-26 01:18 UTC, Bilb commented on ts/components/session/SessionWrapperModal.tsx
> +export const SessionWrapperModal = (props: any) => {
would a lib like react-modal help ?

2021-05-26 01:18 UTC, Bilb commented on background_test.html
> +  <script type='text/javascript' src='js/views/onion_status_dialog_view.js'></script>
you don't need that anymore now that the dialog is reactified or do you?

2021-05-26 01:18 UTC, Bilb commented on js/background.js
> +    };
you don't need that anymore now that the dialog is reactified or do you?

2021-05-26 01:18 UTC, Bilb commented on background.html
> +  <script type='text/javascript' src='js/views/onion_status_dialog_view.js'></script>
you don't need that anymore now that the dialog is reactified or do you?

2021-05-26 01:18 UTC, Bilb commented on js/modules/signal.js
> +const { OnionStatusDialog } = require('../../ts/components/OnionStatusDialog');
you don't need that anymore now that the dialog is reactified or do you?

2021-05-26 01:18 UTC, Bilb commented on js/views/app_view.js
>      showResetSessionIdDialog() {
you don't need that anymore now that the dialog is reactified or do you?

2021-05-26 01:18 UTC, Bilb commented on js/views/onion_status_dialog_view.js
> +  Whisper.OnionStatusDialogView = Whisper.View.extend({
you don't need that anymore now that the dialog is reactified or do you?

2021-05-26 01:18 UTC, Bilb commented on ts/components/OnionStatusDialog.tsx
> +const OnionPathModalInner = (props: any) => {
good splitting of components :+1:

2021-05-26 01:18 UTC, Bilb commented on ts/components/OnionStatusDialog.tsx
> +      <StatusLight color={Constants.UI.COLORS.GREEN}></StatusLight>
use useTheme as said somewhere else to get the color based on the theme

2021-05-26 01:18 UTC, Bilb commented on ts/components/session/ActionsPanel.tsx
> +    let statusColor = Constants.UI.COLORS.DANGER;
use useTheme

2021-05-26 01:18 UTC, Bilb commented on ts/components/session/ActionsPanel.tsx
> +      return <StatusLight isSelected={isSelected} color={Constants.UI.COLORS.DANGER}></StatusLight>;
and there too

2021-05-26 01:18 UTC, Bilb commented on ts/components/session/ActionsPanel.tsx
> +              : Constants.UI.COLORS.DANGER;
and there :)

2021-05-26 01:23 UTC, Bilb commented
> this pulls in a package that does http requests to some remote server to fetch data, suggest using a local geoip database instead.

Which one is making http request?
https://github.com/richorama/country-code-lookup is all offline https://github.com/richorama/country-code-lookup/blob/master/index.js
and https://www.npmjs.com/package/ip2country mapping is built at publish time: `Distributed as a stand-alone NPM module with no dependencies, the list is created at publication time`

2021-05-31 02:02 UTC, Bilb commented
> > this pulls in a package that does http requests to some remote server to fetch data, suggest using a local geoip database instead.
> 
> Which one is making http request?
> https://github.com/richorama/country-code-lookup is all offline https://github.com/richorama/country-code-lookup/blob/master/index.js
> and https://www.npmjs.com/package/ip2country mapping is built at publish time: `Distributed as a stand-alone NPM module with no dependencies, the list is created at publication time`
@majestrate did you find anything else making http request and exposing the user ip?

2021-05-31 10:06 UTC, majestrate commented
> > > this pulls in a package that does http requests to some remote server to fetch data, suggest using a local geoip database instead.
> > 
> > 
> > Which one is making http request?
> > https://github.com/richorama/country-code-lookup is all offline https://github.com/richorama/country-code-lookup/blob/master/index.js
> > and https://www.npmjs.com/package/ip2country mapping is built at publish time: `Distributed as a stand-alone NPM module with no dependencies, the list is created at publication time`
> > @majestrate did you find anything else making http request and exposing the user ip?

yeah looks like i read it wrong, nevermind

2021-06-03 08:49 UTC, Bilb requested changes

2021-06-03 08:49 UTC, Bilb commented on js/background.js
> +          .getConversationController()
this can be ConversationController.getInstance() once moved to ts

2021-06-03 08:49 UTC, Bilb commented on ts/components/OnionStatusDialog.tsx
> +    <>
no need of the <> </> if there is only a single root component rendered

2021-06-03 08:49 UTC, Bilb commented on ts/components/OnionStatusDialog.tsx
> +          <>
no need of the <>

2021-06-03 08:49 UTC, Bilb commented on ts/components/OnionStatusDialog.tsx
> +            ></OnionNodeStatusLight>
could just wrap it with 
```
 <OnionNodeStatusLight
              glowDuration={glowDuration}
              glowStartDelay={index}
              label={snode.label}
              snode={snode}
            /> // the />
            ```

2021-06-03 08:49 UTC, Bilb commented on ts/components/session/ActionsPanel.tsx
> +  const { setModal, type, avatarPath, hasOnionPath } = props;
if `hasOnionPath` is already in redux you should be able to just use it with a `useSelector`

2021-06-03 08:49 UTC, Bilb commented on ts/components/session/ActionsPanel.tsx
> +
we should probably move that to another component which is rendered when  `SectionType.PathIndicator` is set

2021-06-03 08:49 UTC, Bilb commented on ts/components/session/ActionsPanel.tsx
> +    <>
again no need for the <>

2021-06-03 08:49 UTC, Bilb commented on ts/components/session/ActionsPanel.tsx
> +      <Section setModal={setModal} type={SectionType.Moon} />
maybe make thr setModal props optional so we don't need to pass it when not needed?

2021-06-03 08:49 UTC, Bilb commented on ts/components/session/SessionWrapperModal.tsx
> +        props.onClose();
there is weird syntax to avoid this, not sure you want to use it but if yes it looks like that I think
`props.onClose.?()`

2021-06-03 08:49 UTC, Bilb commented on ts/components/session/icon/SessionIcon.tsx
> +      ${glow(props.iconColor, props.glowDuration, props.glowStartDelay)} ${2}s ease-in infinite;
why the `${2}` ? it was dynamic at some point ?

2021-06-03 08:49 UTC, Bilb commented on ts/session/onions/index.ts
> +      window.inboxStore?.dispatch(updateOnionPaths({ path: new Array<Snode>(), bad: true }));
you can just do `{ path: [], bad: true }`

2021-06-03 08:49 UTC, Bilb commented on ts/state/ducks/onion.tsx
> +    bad: false,
might be good to start with a  bad path no? Or does redux starts too late and the first path is already built when we get here and so we don't get the event from the dispatch of new onion path?

2021-06-03 08:49 UTC, Bilb commented on ts/state/ducks/onion.tsx
> +    },
createSlice take care of not triggering update if the state did not change. 
So you can basically return `{ snodePath: action.payload }` directly if I get this correctly. No need to compare it.

and If you need to compare records, no need to put them in json. Use `_.deepEqual` from `lodash`

2021-06-03 08:49 UTC, Bilb commented on ts/window.d.ts
> +    getConversationController: () => ConversationController;
this one has to be removed. 
in typescript you just do `ConversationController.getInstance()` to get the conversation controller

2021-06-03 08:49 UTC, Bilb commented on ts/window.d.ts
> +    commitProfileEdits: (string, string) => void;
those must be removed too once you moved those function to some typescript function you can import. Ask me if needed

2021-06-03 23:59 UTC, Bilb commented on js/background.js
> +    }
this to move to ts

2021-06-21 01:48 UTC, closed without merging