fix: focustrap when no buttons are mounted right away
oxen-io/session-desktop pull request #3074
Opened 2024-04-09 00:15 UTC by Bilb

2024-04-09 22:37 UTC, yougotwill requested changes

2024-04-09 22:37 UTC, yougotwill commented on ts/components/SessionFocusTrap.tsx
> + * This component renders the children inside a FocusTrap and always adds an invisible button to make FocusTrap happy.
I have come up with a slightly cleaner solution in my opinion. Have tested on my machine and confirmed working. Can you update your code and test please? We can also should test on windows to be 100% through.

```tx
import FocusTrap from 'focus-trap-react';
import React, { ReactNode, useState } from 'react';
import { useMount } from 'react-use';

type Props = {
  children: ReactNode;
};

export function SessionFocusTrap(props: Props) {
  const [active, setActive] = useState(false);

  useMount(() => setActive(true));

  return (
    <FocusTrap active={active} focusTrapOptions={{ initialFocus: false, allowOutsideClick: true }}>
      {props.children}
    </FocusTrap>
  );
}

```

2024-04-09 23:21 UTC, yougotwill requested changes

2024-04-09 23:21 UTC, yougotwill commented on ts/components/SessionFocusTrap.tsx
> +import useMount from 'react-use/lib/useMount';
Can the import not be just 'react-use'?

2024-04-09 23:29 UTC, Bilb commented on ts/components/SessionFocusTrap.tsx
> +import useMount from 'react-use/lib/useMount';
resolved

2024-04-09 23:34 UTC, yougotwill approved these changes

2024-04-10 00:58 UTC, Bilb commented
confirmed fine on windows too 
![image](https://github.com/oxen-io/session-desktop/assets/1544279/6d704338-5493-4830-9dd6-8b76752ea9bd)

2024-04-10 01:06 UTC, yougotwill commented
LGTM! 🚢

2024-04-11 23:24 UTC, yougotwill approved these changes
LGTM 🚢

2024-04-11 23:34 UTC, merged